-- Users
INSERT INTO public.users (id, name, api_key) VALUES (1, 'Joe', '9e44bed1ab8845508297079d4a0117b4');

-- Jokes
INSERT INTO public.jokes (intro, punchline, user_id)
VALUES
    ('What did one pirate say to the other when he beat him at chess?','Checkmatey.',1),
    ('I burned 2000 calories today','I left my food in the oven for too long.',1),
    ('I startled my next-door neighbor with my new electric power tool.','I had to calm him down by saying “Don''t worry, this is just a drill!”',1),
    ('I broke my arm in two places.','My doctor told me to stop going to those places.',1),
    ('I quit my job at the coffee shop the other day.','It was just the same old grind over and over.',1),
    ('I never buy anything that has Velcro with it...','it''s a total rip-off.',1),
    ('I used to work at a soft drink can crushing company...','it was soda pressing.',1),
    ('I wondered why the frisbee kept on getting bigger.','Then it hit me.',1),
    ('I was going to tell you a fighting joke...','but I forgot the punch line.',1),
    ('What is the most groundbreaking invention of all time?','The shovel. ',1),
    ('I''m starting my new job at a restaurant next week.','I can''t wait.',1),
    ('I visited a weight loss website...','they told me I have to have cookies disabled.',1),
    ('Did you hear about the famous Italian chef that recently died?','He pasta way.',1),
    ('Broken guitar for sale','no strings attached.',1),
    ('I could never be a plumber','it''s too hard watching your life''s work go down the drain.',1),
    ('I cut my finger slicing cheese the other day...','but I think I may have grater problems than that.',1),
    ('What time did you go to the dentist yesterday?','Tooth-hurty.',1),
    ('What kind of music do astronauts listen to?','Neptunes.',1),
    ('Rest in peace, boiled water.','You will be mist.',1),
    ('What is the only concert in the world that costs 45 cents?','50 Cent, featuring Nickelback.',1),
    ('It''s not a dad bod','it''s a father figure.',1),
    ('My wife recently went on a tropical food diet and now our house is full of this stuff.','It''s enough to make a mango crazy.',1),
    ('What do you call Santa''s little helpers?','Subordinate clauses.',1),
    ('Want to hear a construction joke?','Sorry, I''m still working on it.',1),
    ('What''s the difference between a hippo and a zippo?','One is extremely big and heavy, and the other is a little lighter.',1),
    ('I burnt my Hawaiian pizza today in the oven,','I should have cooked it on aloha temperature.',1),
    ('Anyone can be buried when they die','but if you want to be cremated then you have to urn it.',1),
    ('Where did Captain Hook get his hook?','From the second-hand store.',1),
    ('I am such a good singer that people always ask me to sing solo','solo that they can''t hear me. ',1),
    ('I am such a good singer that people ask me to sing tenor','tenor twelve miles away.',1),
    ('Occasionally to relax I just like to tuck my knees into my chest and lean forward.','That''s just how I roll.',1),
    ('What did the glass of wine say to the glass of beer? Nothing.','They barley knew each other.',1),
    ('I''ve never trusted stairs.','They are always up to something.',1),
    ('Why did Shakespeare''s wife leave him?','She got sick of all the drama.',1),
    ('I just bought a dictionary but all of the pages are blank.','I have no words to describe how mad I am.',1),
    ('If you want to get a job at the moisturizer factory...','you''re going to have to apply daily.',1),
    ('I don''t know what''s going to happen next year.','It''s probably because I don''t have 2020 vision.',1),
    ('Want to hear a joke about going to the bathroom?','Urine for a treat.',1),
    ('I couldn''t figure out how to use the seat belt.','Then it just clicked.',1),
    ('I got an email the other day teaching me how to read maps backwards','turns out it was just spam.',1),
    ('I''m reading a book about anti-gravity.','It''s impossible to put down!',1),
    ('You''re American when you go into the bathroom, and you''re American when you come out, but do you know what you are while you''re in there?','European.',1),
    ('Did you know the first French fries weren''t actually cooked in France?','They were cooked in Greece.',1),
    ('Want to hear a joke about a piece of paper? Never mind...','it''s tearable.',1),
    ('I just watched a documentary about beavers.','It was the best dam show I ever saw!',1),
    ('If you see a robbery at an Apple Store what re you?','An iWitness?',1),
    ('Spring is here!','I got so excited I wet my plants!',1),
    ('What''s Forrest Gump''s password?','1forrest1',1),
    ('Why did the Clydesdale give the pony a glass of water?','Because he was a little horse!',1),
    ('CASHIER: "Would you like the milk in a bag, sir?"','DAD: "No, just leave it in the carton!''”',1),
    ('Did you hear about the guy who invented Lifesavers?','They say he made a mint.',1),
    ('I bought some shoes from a drug dealer.','I don''t know what he laced them with, but I was tripping all day!',1),
    ('Why do chicken coops only have two doors?','Because if they had four, they would be chicken sedans!',1),
    ('How do you make a Kleenex dance?','Put a little boogie in it!',1),
    ('A termite walks into a bar and asks','"Is the bar tender here?"',1),
    ('Why did the invisible man turn down the job offer?','He couldn''t see himself doing it.',1),
    ('I used to have a job at a calendar factory','but I got the sack because I took a couple of days off.',1),
    ('A woman is on trial for beating her husband to death with his guitar collection. Judge says, "First offender?"','She says, "No, first a Gibson! Then a Fender!”',1),
    ('How do you make holy water?','You boil the hell out of it.',1),
    ('I had a dream that I was a muffler last night.','I woke up exhausted!',1),
    ('Did you hear about the circus fire?','It was in tents!',1),
    ('Don''t trust atoms.','They make up everything!',1),
    ('How many tickles does it take to make an octopus laugh?','Ten-tickles.',1),
    ('I''m only familiar with 25 letters in the English language.','I don''t know why.',1),
    ('Why did the cow in the pasture get promoted at work?','Because he is OUT-STANDING in his field!',1),
    ('What do prisoners use to call each other?','Cell phones.',1),
    ('Why couldn''t the bike standup by itself?','It was two tired.',1),
    ('Who was the fattest knight at King Arthur''s round table?','Sir Cumference. ',1),
    ('Did you see they made round bails of hay illegal in Wisconsin?','It''s because the cows weren''t getting a square meal.',1),
    ('You know what the loudest pet you can get is?','A trumpet.',1),
    ('What do you get when you cross a snowman with a vampire?','Frostbite.',1),
    ('What do you call a deer with no eyes?','No idea!',1),
    ('Can February March?','No, but April May!',1),
    ('What do you call a lonely cheese?','Provolone.',1),
    ('Why can''t you hear a pterodactyl go to the bathroom?','Because the pee is silent.',1),
    ('What did the buffalo say to his son when he dropped him off at school?','Bison.',1),
    ('What do you call someone with no body and no nose?','Nobody knows.',1),
    ('You heard of that new band 1023MB?','They''re good but they haven''t got a gig yet.',1),
    ('Why did the crab never share?','Because he''s shellfish.',1),
    ('How do you get a squirrel to like you?','Act like a nut.',1),
    ('Why don''t eggs tell jokes?','They''d crack each other up.',1),
    ('Why can''t a nose be 12 inches long?','Because then it would be a foot.',1),
    ('Did you hear the rumor about butter?','Well, I''m not going to spread it!',1),
    ('I made a pencil with two erasers.','It was pointless.',1),
    ('I used to hate facial hair...','but then it grew on me.',1),
    ('I decided to sell my vacuum cleaner—','it was just gathering dust!',1),
    ('I had a neck brace fitted years ago','and I''ve never looked back since.',1),
    ('You know, people say they pick their nose,','but I feel like I was just born with mine.',1),
    ('What do you call an elephant that doesn''t matter?','An irrelephant.',1),
    ('What do you get from a pampered cow?','Spoiled milk.',1),
    ('It''s inappropriate to make a ''dad joke'' if you''re not a dad.','It''s a faux pa.',1),
    ('How do lawyers say goodbye?','Sue ya later!',1),
    ('Wanna hear a joke about paper?','Never mind—it''s tearable.',1),
    ('What''s the best way to watch a fly fishing tournament?','Live stream.',1),
    ('I could tell a joke about pizza,','but it''s a little cheesy.',1),
    ('When does a joke become a dad joke?','When it becomes apparent.',1),
    ('What''s an astronaut''s favorite part of a computer?','The space bar.',1),
    ('What did the shy pebble wish for?','That she was a little boulder.',1),
    ('I''m tired of following my dreams.','I''m just going to ask them where they are going and meet up with them later.',1),
    ('Did you hear about the guy whose whole left side was cut off?','He''s all right now.',1),
    ('Why didn''t the skeleton cross the road?','Because he had no guts.',1),
    ('What did one nut say as he chased another nut?','I''m a cashew!',1),
    ('Chances are if you'' ve seen one shopping center...','you''ve seen a mall.',1),
    ('I knew I shouldn''t steal a mixer from work...','but it was a whisk I was willing to take.',1),
    ('How come the stadium got hot after the game?','Because all of the fans left.',1),
    ('Why was it called the dark ages?','Because of all the knights. ',1),
    ('Why did the tomato blush?','Because it saw the salad dressing.',1),
    ('Did you hear the joke about the wandering nun?','She was a roman catholic.',1),
    ('What creature is smarter than a talking parrot?','A spelling bee.',1),
    ('I''ll tell you what often gets over looked...','garden fences.',1),
    ('Why did the kid cross the playground?','To get to the other slide.',1),
    ('Why do birds fly south for the winter?','Because it''s too far to walk.',1),
    ('What is a centipedes''s favorite Beatle song?','I want to hold your hand, hand, hand, hand...',1),
    ('My first time using an elevator was an uplifting experience.','The second time let me down.',1),
    ('To be Frank...','I''d have to change my name.',1),
    ('Slept like a log last night …','woke up in the fireplace.',1),
    ('Why does a Moon-rock taste better than an Earth-rock?','Because it''s a little meteor.',1),
    ('How many South Americans does it take to change a lightbulb?','A Brazilian',1),
    ('I don''t trust stairs.','They''re always up to something.',1),
    ('A police officer caught two kids playing with a firework and a car battery.','He charged one and let the other one off.',1),
    ('What is the difference between ignorance and apathy?','I don''t know and I don''t care.',1),
    ('I went to a Foo Fighters Concert once...','It was Everlong...',1),
    ('Some people eat light bulbs.','They say it''s a nice light snack.',1),
    ('What do you get hanging from Apple trees?','Sore arms.',1),
    ('Last night me and my girlfriend watched three DVDs back to back.','Luckily I was the one facing the TV.',1),
    ('I got a reversible jacket for Christmas,','I can''t wait to see how it turns out.',1),
    ('What did Romans use to cut pizza before the rolling cutter was invented?','Lil Caesars',1),
    ('My pet mouse ''Elvis'' died last night.','He was caught in a trap..',1),
    ('Never take advice from electrons.','They are always negative.',1),
    ('Why are oranges the smartest fruit?','Because they are made to concentrate. ',1),
    ('What did the beaver say to the tree?','It''s been nice gnawing you.',1),
    ('How do you fix a damaged jack-o-lantern?','You use a pumpkin patch.',1),
    ('What did the late tomato say to the early tomato?','I''ll ketch up',1),
    ('I have kleptomania...','when it gets bad, I take something for it.',1),
    ('I used to be addicted to soap...','but I''m clean now.',1),
    ('When is a door not a door?','When it''s ajar.',1),
    ('I made a belt out of watches once...','It was a waist of time.',1),
    ('This furniture store keeps emailing me,','all I wanted was one night stand!',1),
    ('How do you find Will Smith in the snow?',' Look for fresh prints.',1),
    ('I just read a book about Stockholm syndrome.','It was pretty bad at first, but by the end I liked it.',1),
    ('Why do trees seem suspicious on sunny days?','Dunno, they''re just a bit shady.',1),
    ('If at first you don''t succeed','sky diving is not for you!',1),
    ('What kind of music do mummy''s like?','Rap',1),
    ('A book just fell on my head.','I only have my shelf to blame.',1),
    ('What did the dog say to the two trees?','Bark bark.',1),
    ('If a child refuses to sleep during nap time...','are they guilty of resisting a rest?',1),
    ('Have you ever heard of a music group called Cellophane?','They mostly wrap.',1),
    ('What did the mountain climber name his son?','Cliff.',1),
    ('Why should you never trust a pig with a secret?','Because it''s bound to squeal.',1),
    ('Why are mummys scared of vacation?','They''re afraid to unwind.',1),
    ('Whiteboards ...','are remarkable.',1),
    ('What kind of dinosaur loves to sleep?','A stega-snore-us.',1),
    ('What kind of tree fits in your hand?','A palm tree!',1),
    ('I used to be addicted to the hokey pokey','but I turned myself around.',1),
    ('How many tickles does it take to tickle an octopus?','Ten-tickles!',1),
    ('What musical instrument is found in the bathroom?','A tuba toothpaste.',1),
    ('My boss told me to attach two pieces of wood together...','I totally nailed it!',1),
    ('What was the pumpkin''s favorite sport?','Squash.',1),
    ('What do you call corn that joins the army?','Kernel.',1),
    ('I''ve been trying to come up with a dad joke about momentum','but I just can''t seem to get it going.',1),
    ('Why don''t sharks eat clowns?','Because they taste funny.',1),
    ('Just read a few facts about frogs.','They were ribbiting.',1),
    ('Why didn''t the melons get married?','Because they cantaloupe.',1),
    ('What''s a computer''s favorite snack?','Microchips!',1),
    ('Why was the robot so tired after his road trip?','He had a hard drive.',1),
    ('Why did the computer have no money left?','Someone cleaned out its cache!',1),
    ('I''m not anti-social.','I''m just not user friendly.',1),
    ('Why did the computer get cold?','Because it forgot to close windows.',1),
    ('What is an astronaut''s favorite key on a keyboard?','The space bar!',1),
    ('What''s the difference between a computer salesman and a used-car salesman?','The used-car salesman KNOWS when he''s lying.',1),
    ('If at first you don''t succeed...','call it version 1.0',1),
    ('Why did Microsoft PowerPoint cross the road?','To get to the other slide!',1),
    ('What did the computer do at lunchtime?','Had a byte!',1),
    ('Why did the computer keep sneezing?','It had a virus!',1),
    ('What did one toilet say to the other?','You look a bit flushed.',1),
    ('Why did the picture go to jail?','Because it was framed.',1),
    ('What did one wall say to the other wall?','I''ll meet you at the corner.',1),
    ('What do you call a boy named Lee that no one talks to?','Lonely',1),
    ('Why do bicycles fall over?','Because they are two-tired!',1),
    ('Why was the broom late?','It over swept!',1),
    ('What part of the car is the laziest?','The wheels, because they are always tired!',1),
    ('What''s the difference between a TV and a newspaper?','Ever tried swatting a fly with a TV?',1),
    ('What did one elevator say to the other elevator?','I think I''m coming down with something!',1),
    ('Why was the belt arrested?','Because it held up some pants!',1),
    ('What makes the calendar seem so popular?','Because it has a lot of dates!',1),
    ('Why did Mickey Mouse take a trip into space?','He wanted to find Pluto!',1),
    ('Why do you go to bed every night?','Because the bed won''t come to you!',1),
    ('What has four wheels and flies?','A garbage truck!',1),
    ('Why did the robber take a bath before he stole from the bank?','He wanted to make a clean get away!',1),
    ('Just watched a documentary about beavers.','It was the best damn program I''ve ever seen.',1),
    ('Slept like a log last night','woke up in the fireplace.',1),
    ('Why did the scarecrow win an award?','Because he was outstanding in his field.',1),
    ('Why does a chicken coop only have two doors?','Because if it had four doors it would be a chicken sedan.',1),
    ('What''s the difference between an African elephant and an Indian elephant?','About 5000 miles',1),
    ('Why did the coffee file a police report?','It got mugged.',1),
    ('What did the grape do when he got stepped on?','He let out a little wine.',1),
    ('How many apples grow on a tree?','All of them.',1),
    ('What name do you give a person with a rubber toe?','Roberto',1),
    ('Did you hear about the kidnapping at school?','It''s fine, he woke up.',1),
    ('Why do scuba divers fall backwards into the water?','Because if they fell forwards they''d still be in the boat.',1),
    ('How does a penguin build it''s house?','Igloos it together.',1),
    ('What do you call a man with a rubber toe?','Roberto',1),
    ('Did you hear about the restaurant on the moon?','Great food, no atmosphere.',1),
    ('Why was the belt sent to jail?','For holding up a pair of pants!',1),
    ('Did you hear about the scientist who was lab partners with a pot of boiling water?','He had a very esteemed colleague.',1),
    ('What happens when a frogs car dies?','He needs a jump. If that doesn''t work he has to get it toad.',1),
    ('What did the flowers do when the bride walked down the aisle?','They rose.',1),
    ('Why did the man fall down the well?','Because he couldn''t see that well.',1),
    ('My boss told me to have a good day...','...so I went home.',1),
    ('How can you tell it''s a dogwood tree?','By the bark.',1),
    ('Did you hear about the kidnapping at school?','It''s fine, he woke up.',1),
    ('Why is Peter Pan always flying?','Because he Neverlands.',1),
    ('Which state has the most streets?','Rhode Island.',1),
    ('What do you call 26 letters that went for a swim?','Alphawetical.',1),
    ('Why was the color green notoriously single?','It was always so jaded.',1),
    ('Why did the coach go to the bank?','To get his quarterback.',1),
    ('How do celebrities stay cool?','They have many fans.',1),
    ('What''s the most depressing day of the week?','sadder day.',1),
    ('Dogs can''t operate MRI machines','But catscan.',1),
    ('I was going to tell a time-traveling joke','but you guys didn''t like it.',1),
    ('Stop looking for the perfect match','instead look for a lighter.',1),
    ('I told my doctor I heard buzzing','but he said it''s just a bug going around.',1),
    ('What kind of car does a sheep like to drive?','A lamborghini.',1),
    ('What did the accountant say while auditing a document?','This is taxing.',1),
    ('What did the two pieces of bread say on their wedding day?','It was loaf at first sight.',1),
    ('Why do melons have weddings?','Because they cantaloupe.',1),
    ('What did the drummer call his twin daughters?','Anna One, Anna Two!',1),
    ('What do you call a toothless bear?','A gummy bear!',1),
    ('Two goldfish are in a tank.','One says to the other, “Do you know how to drive this thing?”',1),
    ('What''s Forrest Gump''s password?','1forrest1',1),
    ('What is a child guilty of if they refuse to nap?','Resisting a rest.',1),
    ('I know a lot of jokes about retired people','but none of them work.',1),
    ('Why are spiders so smart?','They can find everything on the web.',1),
    ('What has one head, one foot, and four legs?','A bed.',1),
    ('What does a house wear?','Address.',1),
    ('What''s red and smells like blue paint?','Red paint.',1),
    ('My son asked me to put his shoes on','but I don''t think they''ll fit me.',1),
    ('I''ve been bored recently, so I decided to take up fencing.','The neighbors keep demanding that I put it back.',1),
    ('What do you call an unpredictable camera?','A loose Canon.',1),
    ('Which U.S. state is known for its especially small soft drinks?','Minnesota.',1),
    ('What do sprinters eat before a race?','Nothing—they fast.',1),
    ('I''m so good at sleeping...','I can do it with my eyes closed.',1),
    ('People are usually shocked that I have a Police record.','But I love their greatest hits!',1),
    ('I told my girlfriend she drew on her eyebrows too high.','She seemed surprised.',1),
    ('What do you call a fibbing cat?','A lion.',1),
    ('Why shouldn''t you write with a broken pencil?','Because it''s pointless.',1),
    ('I like telling Dad jokes…','sometimes he laughs.',1),
    ('How do you weigh a millennial?','In Instagrams.',1),
    ('The wedding was so beautiful','even the cake was in tiers.',1),
    ('What''s the most patriotic sport?','Flag football.',1);
